### ISSUE TITLE
NullPointerException in RecyclerView

### ISSUE THREAD

**Issue by BehnamMaboodi** [twotoasters/JazzyListView#45]
JazzyHelper throws Null Pointer Exception while scroll very (very) fast (only on recyclerview)

```
NullPointerException
System.err:  at jazzylistview.JazzyHelper.doJazzinessImpl(JazzyHelper.java:204)
System.err:  at jazzylistview.JazzyHelper.doJazziness(JazzyHelper.java:195)
System.err:  at jazzylistview.JazzyHelper.onScrolled(JazzyHelper.java:121)
System.err:  at jazzylistview.JazzyRecyclerViewScrollListener.onScrolled(JazzyRecyclerViewScrollListener.java:37)
```

**Comment by ghost** [comment]
Same problem here:

Fatal Exception: java.lang.NullPointerException
       at com.twotoasters.jazzylistview.JazzyHelper.doJazzinessImpl(JazzyHelper.java:197)
       at com.twotoasters.jazzylistview.JazzyHelper.doJazziness(JazzyHelper.java:189)
       at com.twotoasters.jazzylistview.JazzyHelper.onScrolled(JazzyHelper.java:115)
       at com.twotoasters.jazzylistview.recyclerview.JazzyRecyclerViewScrollListener.onScrolled(JazzyRecyclerViewScrollListener.java:24)
       at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:3704)
       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3859)

Is it possible to merge with [this fork](https://github.com/sbaar/JazzyListView/commit/45282922b991742dc7500d584fec7f738c45a670) which seems to avoid the problem?

**Comment by BehnamMaboodi** [comment]
This fork seems useful , I think this will fix the issue. Also You can download the source code and add this lines yourself , I solved this problem by adding a simple "try-catch" statement to the same line.

**Comment by FizaUlfat** [comment]
where should i add try catch statment

**Comment by BehnamMabodi** [comment]
@FizaUlfat Check this [link](https://github.com/sbaar/JazzyListView/commit/45282922b991742dc7500d584fec7f738c45a670)

**Comment by BehnamMaboodi** [comment]
@FizaUlfat Check pull request #51 
You can merge it yourself to your own fork.
